language: generic
addons:
  apt:
    packages:
      - oracle-java8-set-default
install:
  - git clone --depth 1 https://github.com/whatwg/html-build.git ../html-build
  - curl -O https://sideshowbarker.net/nightlies/jar/vnu.jar
script:
  - ../html-build/build.sh
  - java -jar vnu.jar /home/travis/build/whatwg/html-build/output/*.html
notifications:
  email:
    on_success: never
    on_failure: always
